// <auto-generated />
namespace RecipesData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Timestamps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Timestamps));
        
        string IMigrationMetadata.Id
        {
            get { return "202006060741548_Timestamps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
